config/routes.rb
Openphin::Application.routes.draw do
  resources :han_alerts, :only => [:index,:create,:new,:edit,:show,:update] do
      collection do
        get :recent
      end
  end
  match "/han_alerts/index/upload" => "han_alerts#upload", :as => :upload, :method => [:get, :post]
  match "/han_alerts/new/playback.wav" => "han_alerts#playback", :as => :playback, :method => [:get]
  match "/han_alerts/calculate_recipient_count.:format" => "han_alerts#calculate_recipient_count"
end

app/controllers/han_alerts_controller.rb
require 'fileutils'

class HanAlertsController < ApplicationController
  before_filter :alerter_required, :only => [:index, :new, :create, :edit, :update, :calculate_recipient_count]
  before_filter :can_view_alert, :only => [:show]
  skip_before_filter :authorize, :only => [:token_acknowledge, :upload, :playback]
  protect_from_forgery :except => [:upload, :playback]

  app_toolbar "han"

  def index
    @alerts = current_user.han_alerts_within_jurisdictions(params[:page])
  end

  def recent
    require 'will_paginate/array'
    per_page = ( params[:per_page].to_i > 0 ? params[:per_page].to_i : 10 )
    @alerts = (defined?(current_user.recent_han_alerts) && current_user.recent_han_alerts.size > 0) ?
        current_user.recent_han_alerts.paginate(:page => params[:page], :per_page => per_page) :
        (defined?(HanAlert) ? [HanAlert.default_alert] : []).paginate(:page => 1)
    respond_to do |format|
      format.html
      format.ext
      format.json do
        unless @alerts.nil? || @alerts.empty? || ( @alerts.map(&:id) == [nil] ) # for dummy default alert
          jsonObject = @alerts.collect{ |alert| alert.iphone_format(update_alert_path(alert.id),alert.acknowledged_by_user?(current_user)) }
          headers["Access-Control-Allow-Origin"] = "*"
          render :json => jsonObject
        else
          headers["Access-Control-Allow-Origin"] = "*"
          render :json => []
        end
      end
    end
  end

  def show
    alert = HanAlert.find(params[:id])
    @alert = alert
    respond_to do |format|
      format.html
      format.xml { render :xml => @alert.to_xml( :include => [:author, :from_jurisdiction] , :dasherize => false)}
      format.json do
        original_included_root = ActiveRecord::Base.include_root_in_json
        ActiveRecord::Base.include_root_in_json = false
        audiences = {:roles => [], :groups => [], :jurisdictions => [], :users => []}
        alert.audiences.each do |audience|
          if audience.name.nil?
            audiences[:roles] = audiences[:roles] | audience.roles.map {|role| role.as_json(:only => ["id", "name"])}
            audiences[:jurisdictions] = audiences[:jurisdictions] | audience.jurisdictions.map {|jurisdiction| jurisdiction.as_json(:only => ["id", "name"])}
            audiences[:users] = audiences[:users] | audience.users.map {|user| {:id => user.id, :name => user.display_name } }
          else
            audiences[:groups].push(audience.as_json(:only => ["id", "name"]))
          end
        end
        render :json => {:alert => alert.as_json(:include => {:alert_device_types => {:only => ['device']}, :author => {:only => ["display_name"]} },
                                                 :only => ['acknowledge', 'call_down_messages', 'created_at', 'delivery_time', 'message', 'not_cross_jurisdictional', 'severity', 'short_message', 'status', 'sensitive', 'title', 'from_jurisdiction_id']),
                         :alert_attempts => alert.alert_attempts,
                         :audiences => audiences,
                         :recipient_count => @alert.recipients.count
        }
        ActiveRecord::Base.include_root_in_json = original_included_root
      end
   end

  end

  def new
    @alert = HanAlert.new_with_defaults
    @acknowledge_options = HanAlert::Acknowledgement
  end

  def create
    remove_blank_call_downs unless params[:han_alert][:call_down_messages].nil?
    set_acknowledge
    params[:han_alert][:author_id] = current_user.id
    @alert = HanAlert.new(params[:han_alert])
    @acknowledge = if @alert.acknowledge
      @alert.call_down_messages.blank? || @alert.call_down_messages["1"] == "Please press one to acknowledge this alert." ? 'Normal' : 'Advanced'
    else
      'None'
    end
    @acknowledge_options = HanAlert::Acknowledgement

    if params[:send]
      if @alert.valid?

        @alert.save
        #@alert.integrate_voice
        #@alert.batch_deliver
        respond_to do |format|
          format.html {
            flash[:notice] = "Successfully sent the alert."
            redirect_to han_alerts_path
          }
          format.json { render :json => {:success => true, :alert_path => alert_path(@alert), :id => @alert.id, :title => @alert.title}}
        end
      else
        if @alert.errors['message_recording']
          flash[:error] = "Attached message recording is not a valid wav formatted file."
          @preview = true
        end
        respond_to do |format|
          format.html { render :new }
          format.json { render :json => @alert.errors, :status => :unprocessable_entity}
        end
      end
    else
      @preview = true
      @token = current_user.token
      @num_recipients = 0
      render :new
    end
  end

  def edit
    alert = HanAlert.find params[:id]

    error = false
    msg = nil

    if alert.nil?
      msg = "You do not have permission to update or cancel this alert."
      error = true
    end

    unless error
      @acknowledge_options = HanAlert::Acknowledgement #.reject{|x| x=="Advanced"}
      # TODO : Remove when devices refactored
      @device_types = []
      alert.device_types.each do |device_type|
        @device_types << device_type
      end
      @acknowledge = if alert.acknowledge?
        alert.call_down_messages.blank? || alert.call_down_messages["1"] == "Please press one to acknowledge this alert." ? 'Normal' : 'Advanced'
      else
        'None'
      end
    end

    unless alert.is_updateable_by?(current_user)
      msg = "You do not have permission to update or cancel this alert."
      error = true
    end

    unless alert.original_alert.nil?
      msg = "You cannot make changes to updated or cancelled alerts."
      error = true
    end

    if alert.cancelled?
      msg = "You cannot update or cancel an alert that has already been cancelled."
      error = true
    end

    if error
      respond_to do |format|
        format.html do
          flash[:error] = msg
          redirect_to han_alerts_path
        end
        format.json {render :json => {'success' => false, 'msg' => msg}, :status => 401}
      end
      return
    end

    respond_to do |format|
      format.html do
        @alert = alert
        @update = true if params[:_action].downcase == "update"
        @cancel = true if params[:_action].downcase == "cancel"
      end
      format.json do
        audiences = {:roles => [], :groups => [], :jurisdictions => [], :users => []}
        alert.audiences.each do |audience|
          if audience.name.nil?
            audiences[:roles] = audiences[:roles] | audience.roles
            audiences[:jurisdictions] = audiences[:jurisdictions] | audience.jurisdictions
            audiences[:users] = audiences[:users] | audience.users
          else
            audiences[:groups].push(audience)
          end
        end
        render :json => {'alert' => alert, 'devices' => @device_types, 'audiences' => audiences, 'success' => true, 'recipient_count' => alert.recipients.count}
      end
    end
  end

  def update
    original_alert = HanAlert.find params[:id]
    # TODO : Remove when devices refactored
    @device_types = []
    original_alert.device_types.each do |device_type|
      @device_types << device_type
    end

    unless original_alert.is_updateable_by?(current_user)
      msg = "You do not have permission to update or cancel this alert."
      respond_to do |format|
        format.html do
          flash[:error] = msg
          redirect_to han_alerts_path
        end
        format.json {render :json => {'message' => msg, 'success' => false}, :status => 401}
      end
    end

    if original_alert.cancelled?
      msg = "You cannot update or cancel an alert that has already been cancelled."
      respond_to do |format|
        format.html do
          flash[:error] = msg
          redirect_to han_alerts_path
        end
        format.json {render :json => {'message' => msg, 'success' => false}, :status => 401}
      end
      return
    end
    reduce_call_down_messages_from_responses(original_alert)
    set_acknowledge
    @alert = if params[:_action].downcase == 'cancel'
      @cancel = true
      original_alert.build_cancellation(params[:han_alert])
    elsif params[:_action].downcase == 'update'
      @update = true
      original_alert.build_update(params[:han_alert])
    end
    @acknowledge = if @alert.acknowledge
      'Normal'
    else
      'None'
    end
     @acknowledge_options = HanAlert::Acknowledgement #.reject{|x| x=="Advanced"}
    if params[:send]
      @alert.save
      if @alert.valid?
        #@alert.integrate_voice
        #@alert.batch_deliver
        respond_to do |format|
          format.html do
            flash[:notice] = "Successfully sent the alert."
            redirect_to han_alerts_path
          end
          format.json {render :json => {'success' => true}}
        end
      else
        if @alert.errors['message_recording']
          msg = "Attached message recording is not a valid wav formatted file."
          respond_to do |format|
            format.html do
              flash[:error] = msg
              @preview = true
              render :new
            end
            format.json {render :json => {'message' => msg, 'success' => false}, :status => 406}
          end
        end
      end
    else
      @alert = @alert
      @preview = true
      render :edit
    end
  end

  def calculate_recipient_count
    parms = { :audience => {:jurisdiction_ids => params[:jurisdiction_ids], :user_ids => params[:user_ids], 
              :role_ids => params[:role_ids], :group_ids => params[:group_ids]},
              :not_cross_jurisdictional => params[:not_cross_jurisdictional],
              :from_jurisdiction_id => params[:from_jurisdiction_id]}
    respond_to do |format|
        format.json { render :json => HanAlert.preview_recipients_size(parms) }
    end
  end

  def upload

app/helpers/han_alerts_helper.rb
module HanAlertsHelper

  def acknowledge_alert_button(alert, options = {:response => "1"})
    if alert.ask_for_acknowledgement?(current_user)
      button_to 'Acknowledge', update_alert_path(alert.id, options), :method => :put
    end
  end
end

# form.object.jurisdiction_ids.include?(item.id)

app/views/han_alerts/_alert.ext.erb
<%= content_tag_for :li, alert, :class => 'han_alert' do %>
  <div class="summary">
    <p class="title">
      <span class="title <%=h alert.severity.downcase %>"><%=h alert.title %></span>
    </p>
    <p class="meta">
      <span class="created_at">Posted at <%= alert.created_at.strftime("%B %d, %Y %I:%M %p %Z") %> <%= 'by '+link_to(h(alert.author.display_name), user_profile_path(alert.author)) unless alert.author.blank? || alert.author.display_name.blank? %></span>
      <%- if alert.status.blank? || alert.status.downcase != "actual" -%>
        <span class="status <%=h alert.status.downcase %>"><strong>Status:</strong> [<%=h alert.status.capitalize %>]</span>
      <%- end -%>
      <span class="severity <%=h alert.severity %>"><strong>Severity:</strong> <%=h alert.severity %></span>
      <span class="from_jurisdiction"><strong>From:</strong> <%=h alert.sender %></span>
    </p>
  </div>
  <div class="extended preview">
    <div class="details">
      <p class="brief"><strong>Alert ID:</strong> <%=h alert.identifier %></p>
      <p class="brief sensitive"><strong>Sensitive:</strong> <%=h alert.sensitive? ? 'Yes' : 'No' %></p>
      <p class="brief acknowledge alertResponse"><strong>Acknowledge:</strong> <%=
          if alert.acknowledge?
            unless alert.alert_attempts.find_by_user_id(current_user.id).nil?
              cdr = alert.alert_attempts.find_by_user_id(current_user.id).call_down_response
              if alert.call_down_messages[cdr.to_s] == "Please press one to acknowledge this alert."
                alert.acknowledge? ? 'Yes' : 'No'
              else
                h(alert.call_down_messages[cdr.to_s])
              end if cdr
            end
          end
      %></p>


      <%- if !alert.original_alert_id.blank? -%>
        <p class="brief"><strong>Reference ID:</strong> <%=h alert.original_alert.identifier %></p>
      <%- end -%>
      <div class="message">
        <%=simple_format h(alert.message) %>
      </div>

      <p>
        <% if alert.acknowledge? && !alert.acknowledged_by_user?(current_user) %>
          <% if alert.expired? %>
            Acknowledgement is no longer allowed for this Alert.
          <% elsif alert.call_down_messages["1"] == "Please press one to acknowledge this alert." %>
            <%= acknowledge_alert_button(alert) %>
          <% else %>
            <%= form_tag update_alert_path(alert.id), :method => :put do  %>
              <%= label_tag "response", "Alert Response" %>
              <%= select_tag("response", options_for_select(alert.call_down_messages.collect{|k,v|[v,k]}),{ :prompt => "Select a response" }) %>
              <p><%= submit_tag "Acknowledge" %></p>
            <% end %>
        <% end %>
      <% end %>
      </p>

    </div>
  </div>
<%- end -%>

app/views/han_alerts/_alert_acknowledgements.html.erb
<h3>Acknowledgments (by jurisdiction)</h3>
<div class="jur_ackpct">
  <% alert.ack_logs.find_all_by_item_type("jurisdiction", :order => :item).each do |jur| %>
    <h5 class="jurisdiction"><%= h jur.item %></h5>

    <p class="percentage"><%= (jur.acknowledged_percent * 100).round %>%</p>
  <% end %>
</div>

<h3>Acknowledgments (by device)</h3>
<div class="dev_ackpct">
  <% alert.ack_logs.find_all_by_item_type("device").each do |device| %>
    <% name = AlertDeviceType.find_by_device(device.item).device_type.display_name %>
    <div class="<%= h name %>">
      <h5 class="device_type"><%= h name %></h5>

      <p class="percentage"><%= (device.acknowledged_percent * 100).round %>%</p>
    </div>
  <% end  %>
</div>

<h3>Acknowledgments (by alert response)</h3>
<div class="response_ackpct">
  <% alert.ack_logs.find_all_by_item_type("alert_response").each do |response| %>
    <div id="response<%= h alert.call_down_messages.key(response.item) %>">
      <h5><%= h response.item %></h5>
      
      <p class="percentage"><%= (response.acknowledged_percent * 100).round %>%</p>
    </div>
  <% end %>
</div>

app/views/han_alerts/_han_alert.html.erb
<h2 class="title"><%=h @alert.title %></h2>

<div class="alert">

  <div class="details">
    <%=simple_format h(@alert.message), :class => 'message' %>
    <p><strong>Short Message:</strong> <%= h(@alert.short_message) %></p>
    <p class="author"><strong>Author: </strong><%= @alert.author.display_name %></p>
    <% unless @alert.created_at.nil? %>
      <p class="created_at"><strong>Created at: </strong><%= @alert.created_at.strftime("%B %d, %Y %I:%M %p %Z") %></p>
    <% end %>
    <p class="not_cross_jurisdictional"><strong>Disable Cross-Jurisdictional alerting?:</strong> <%=h yn(@alert.not_cross_jurisdictional?) %></p>
    <% if @alert.acknowledge? %>
      <% @alert.call_down_messages.each do |index, value| %>
        <p class="alertResponse"><strong>Alert Response <%=h index %>:</strong> <%=h value %></p>
      <% end %>
     <% end %>
  </div>

  <div class="aside">
    <h5>Severity</h5>
    <p class="severity"><%=h @alert.severity %></p>

    <h5>Status</h5>
    <p class="status"><%=h @alert.status %></p>

    <h5>Acknowledge</h5>
    <p class="acknowledge">
      <%- if @alert.acknowledge? -%>
        <%= @alert.call_down_messages["1"] == "Please press one to acknowledge this alert." && @alert.original_alert.nil? ? "Advanced" : "Normal" -%>
      <%- else -%>
        None
      <%- end -%>
    </p>

    <h5>Sensitive</h5>
    <p class="sensitive"><%=h yn(@alert.sensitive?) %></p>

    <h5>Delivery Time</h5>
    <p class="delivery_time"><%=h @alert.human_delivery_time %></p>

    <h5>Methods</h5>
    <p class="communication_methods"><%= @alert.device_types.map{|d| d.constantize.display_name }.to_sentence %></p>

    <%- unless @alert.caller_id.blank? -%>
      <h5>Caller ID</h5>
      <p class="caller_id"><%= @alert.caller_id %></p>
    <%- end -%>

  </div>

</div>


<div class="audience" >
  <br/>
  <h3>Audience</h3>
  <% @alert.audiences.each do |audience| %>
    <p class="jurisdictions"><strong>Jurisdictions:</strong> <%=h audience.jurisdictions.blank? ? 'None' : audience.jurisdictions.map(&:name).to_sentence %></p>

    <p class="roles"><strong>Roles:</strong> <%=h audience.roles.blank? ? 'None' : audience.roles.map(&:name).to_sentence %></p>

    <p class="people"><strong>People:</strong> <%=h audience.users.blank? ? 'No additional people selected' : audience.users.map(&:name).to_sentence %></p>
  <% end %>
  <p class="num_of_recipients"><strong># of Recipients: </strong><%= @alert.new_record? ? HanAlert.preview_recipients_size(params) : @alert.alert_attempts.count %></p>
</div>

<div class="contacted_users" >
  <br/>
  <h3>Contacted Users</h3>
  <% unless @alert.new_record? %>
    <%= link_to "Export Contacted Users (CSV)", han_alert_path(@alert,:format=>:csv) %>
  <% end %>

  <% attempts = @alert.alert_attempts.paginate(:page=>params[:page]||1,:per_page=>8, :include => :user, :order => "users.display_name") %>
  <%= will_paginate attempts %>
  <table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <% if @alert.acknowledge  %>
        <th>Acknowledged with Device</th>
        <th>Alert Response</th>
        <th>Acknowledgement Time</th>
      <% end %>
      </tr>
      <% attempts.each do |attempt| %>
        <tr class="user" style="border-top: 1px lightgray solid;" >
        <td class="name"><%= attempt.user ? attempt.user.display_name : attempt.jurisdiction ? attempt.jurisdiction.name : '' %> </td>
        <td class="email"><%= attempt.user ? attempt.user.email : ''%> </td>
        <% if @alert.acknowledge  %>
          <td class="device_type"><%= attempt.acknowledged_alert_device_type.device.constantize.display_name unless attempt.acknowledged_alert_device_type.nil? %></td>
          <td class="alert_response"><%=
            unless attempt.call_down_response.nil?
              if (attempt.call_down_response == 0)
                "<span style='font-size: 180%; font-weight: bold;'>&#x2713</span>"
   	          else
  	            @alert.call_down_messages[attempt.call_down_response.to_s]
  	          end
  	        else
  	          "<span style='color: #880000; text-align: middle;'> - </span>"
            end
          %></td>
         <td class="alert_ack_time"><%= attempt.acknowledged_at.strftime("%B %d, %Y %I:%M %p %Z") unless attempt.acknowledged_at.nil? %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <br /><%= will_paginate attempts %>
</div>
<% unless @alert.new_record? %>
  <p><%= link_to "Printable Report (PDF)", han_alert_path(@alert,:format=>:pdf) %></p>
<% end %>

app/views/han_alerts/_player.html.erb
<p>
  <div class="player">
    Please use the controls below to review the audio alert message
    <applet
      CODE="com.softsynth.javasonics.recplay.PlayerApplet"
      CODEBASE="/codebase"
      ARCHIVE="JavaSonicsListenUp.jar,OggXiphSpeexJS.jar"
      NAME="JavaSonicRecorderUploader"
      WIDTH="186" HEIGHT="42">
      <param name="bevelSize" value="0">
      <param name="showWaveform" value="no">
      <param name="background" value="FFFFFF">
      <param name="showLogo" value="no">
      <param name="showPauseButton" value="no">
      <param name="showTimeText" value="no">
      <param name="showPositionDisplay" value="no">
      <param name="showVUMeter" value="yes">
      <param name="showWaveform" value="no">
      <param name="arrangement" value="wide">
      <param name="packButtons" value="yes">
      <param name="sampleURL" value="<%= sample_url %>">
      <param name="useURLConnection" value="yes">
    </applet>
  </div>
</p>

app/views/han_alerts/_view_alert.html.erb
<% content_tag_for :li, alert, :class => 'han_alert' do %>
    <div class="summary">
      <p class="title">
        <span class="title <%= alert.severity.downcase %>"><%=h alert.title %></span>
        <span class="actions">
          <%= link_to 'View', han_alert_path(alert.id) %>
          <%= link_to 'Update', edit_han_alert_path(alert, :_action => 'update') if alert.original_alert.nil? && !alert.cancelled? %>
          <%= link_to 'Cancel', edit_han_alert_path(alert, :_action => 'cancel') if alert.original_alert.nil? && !alert.cancelled? %>
        </span>
      </p>
      <p class="meta">
        <span class="created_at">Posted at <%= alert.created_at.strftime("%B %d, %Y %I:%M %p %Z") %> <%= 'by '+link_to(alert.author.display_name, user_profile_path(alert.author)) unless alert.author.blank? || alert.author.display_name.blank? %></span>
        <%- if alert.status.blank? || alert.status.downcase != "actual" -%>
        <span class="status <%= alert.status.downcase %>"><strong>Status:</strong> [<%= alert.status.capitalize %>]</span>
        <%- end -%>
  <span class="severity <%=h alert.severity %>"><strong>Severity:</strong> <%=h alert.severity %></span>
        <span class="from_jurisdiction"><strong>From:</strong> <%=h alert.sender %></span>
        <br/>
  <%- if alert.acknowledge? -%>
        <span class="progress"><strong>Acknowledgments:</strong> <%= alert.acknowledged_percent.round %>%</span>
  <%- end -%>
  </p>
    </div>
  <div class="extended preview">
    <div class="details">
        <p class="brief alertid"><strong>Alert ID:</strong> <%=h alert.identifier %></p>

        <p class="brief"><strong>Sensitive:</strong> <%=h alert.sensitive? ? 'Yes' : 'No' %></p>

      <p class="brief"><strong>Acknowledge:</strong> <%=h alert.acknowledge? ? 'Yes' : 'No' %></p>

        <%- if !alert.original_alert_id.blank? -%>
        <p class="brief"><strong>Reference ID:</strong> <%=h alert.original_alert.identifier %></p>
        <%- end -%>
        <div class="message">
          <%=simple_format h(alert.message) %>
        </div>
      </div>
    <div class="aside">
  <%- if alert.acknowledge? -%>
      <%= render :partial => "alert_acknowledgements", :locals => {:alert => alert} %>
  <%- end -%>
    </div>
    </div>
<%- end -%>

app/views/han_alerts/edit.html.erb
<% form_for @alert, :url => @alert.original_alert, :html => {:method => :put} do |form| %>
  <%= render form %>
<% end %>

app/views/han_alerts/index.html.erb
<h2>Viewing Alerts</h2>

<%= page_entries_info @alerts unless @alerts.empty? %>
<%= paginated_section @alerts do %>
  <ul id="alerts">
    <% @alerts.each do |alert| %>
      <%= content_tag_for :li, alert, :class => 'han_alert' do %>
        <div class="summary">
          <p class="title">
            <span class="title <%= alert.severity.downcase %>"><%= h alert.title %></span>
            <span class="actions">
              <%= link_to 'View', han_alert_path(alert.id) %>
              <%= link_to 'Update', edit_han_alert_path(alert, :_action => 'update') if alert.original_alert.nil? && !alert.cancelled? %>
              <%= link_to 'Cancel', edit_han_alert_path(alert, :_action => 'cancel') if alert.original_alert.nil? && !alert.cancelled? %>
            </span>
          </p>

          <p class="meta">
            <span class="created_at">Posted at <%= alert.created_at.strftime("%B %d, %Y %I:%M %p %Z") %> <%= raw('by '+link_to(alert.author.display_name, user_profile_path(alert.author))) unless alert.author.blank? || alert.author.display_name.blank? %></span>
            <%- if alert.status.blank? || alert.status.downcase != "actual" -%>
                <span class="status <%= alert.status.downcase %>"><strong>Status:</strong> [<%= alert.status.capitalize %>
                  ]</span>
            <%- end -%>
            <span class="severity <%= h alert.severity %>"><strong>Severity:</strong> <%= h alert.severity %></span>
            <span class="from_jurisdiction"><strong>From:</strong> <%= h alert.sender %></span>
            <br/>
            <%- if alert.acknowledge? -%>
              <span class="progress"><strong>Acknowledgments:</strong> <%= (alert.acknowledged_percent * 100).round %>%</span>
            <%- end -%>
          </p>
        </div>
        <div class="extended preview">
          <div class="details">
            <p class="brief alertid"><strong>Alert ID:</strong> <%= h alert.identifier %></p>

            <p class="brief"><strong>Sensitive:</strong> <%= h alert.sensitive? ? 'Yes' : 'No' %></p>

            <%- if alert.acknowledge? -%>
              <%- if alert.call_down_messages["1"] == "Please press one to acknowledge this alert." -%>
                <p class="brief"><strong>Acknowledge:</strong> Normal</p>
              <%- else -%>
                <p class="brief"><strong>Acknowledge:</strong> Advanced</p>
              <%- end -%>
            <%- else -%>
              <p class="brief"><strong>Acknowledge:</strong> None</p>
            <%- end -%>

            <%- if !alert.original_alert_id.blank? -%>
              <p class="brief"><strong>Reference ID:</strong> <%= h alert.original_alert.identifier %></p>
            <%- end -%>
            <div class="message">
              <%= simple_format h(alert.message) %>
            </div>
          </div>
          <div class="aside">
            <%- if alert.acknowledge? -%>
              <%= render :partial => "alert_acknowledgements", :locals => {:alert => alert} %>
            <%- end -%>
          </div>
        </div>
      <%- end -%>
     <%- end -%>
  </ul>
<%- end unless @alerts.empty? -%>

app/views/han_alerts/new.html.erb
<% form_for @alert, :html => { :multipart => true } do |form| %>
  <%= render form %>
<% end %>

app/views/han_alerts/play.html.erb
<%= @file %>

app/views/han_alerts/recent.erb
<ul id="alerts">
  <%= render :partial => "han_alerts/alert", :collection => @alerts, :as => :alert %>
  <%= will_paginate @alerts %>
</ul>

app/views/han_alerts/show.html.erb
<% div_for @alert do %>
	<%= render :partial => "han_alert" %>
	<%= button_to 'Back', :back, :method => :get %>
<% end %>

app/views/han_alerts/upload_error.html.erb
ERROR

app/views/han_alerts/upload_warning.html.erb
WARNING